### ISSUE TITLE
can we change scout 2

### ISSUE THREAD

**Issue by himhan34** [agilexrobotics/scout_ros#13]
can we change the wheel encoder hz? with the scout 2?

**Comment by agilexrobotics** [comment]
The feedback message in can bus is 50hz,so the ros package can get msg of encoder with max speed 50hz.If you want more faster, we have to change the firmware of scout 2 which means the scout will be custom.

**Comment by himhan34** [comment]
if you are okay, can you tell me more about that? 
i mean I want to change the hz of the wheel encoder, lower or higher. 
and if the firmware modification is needed i will do !  
thanks !

**Comment by lagrangeluo** [comment]
> if you are okay, can you tell me more about that? i mean I want to change the hz of the wheel encoder, lower or higher. and if the firmware modification is needed i will do ! thanks !

Hi! I don't know if you still need some help for this now, I think you should contact to our sales because the firmware is part of our standard products so you should contact to your sales to go through a customized process which means some extra fee.I can't modify our firmware on the microcontroller without permission sorry
